AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'bin/**/*'
    - 'Guardfile'
    - 'Vagrantfile'
    - 'spec/support/share_db_connection.rb'
    - 'spec/acceptance/steps/common_steps.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
