source 'https://rubygems.org'

ruby '2.1.2'

gem 'rails', '~> 4.1.1'

gem 'active_model_serializers'
gem 'awesome_print'
gem 'bcrypt', '~> 3.1.7'
gem 'bitfields'
gem 'bootstrap-datepicker-rails'
gem 'bootstrap-sass', '~> 3.1.1'
gem 'carrierwave'
gem 'chronic'
gem 'coffee-rails', '~> 4.0.0'
gem 'country_select'
gem 'crypt_keeper'
gem 'dalli'
gem 'devise'
gem 'ffaker'
gem 'fog'
gem 'friendly_id'
gem 'geocoder'
gem 'gmaps4rails'
gem 'gravatar_image_tag'
gem 'hiredis'
gem 'ids_please'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'kaminari'
gem 'kgio'
gem 'mail_view'
gem 'mandrill-api'
gem 'memcachier'
gem 'multi_json'
gem 'oj'
gem 'paper_trail', '~> 3.0.2'
gem 'party_foul'
gem 'pg'
gem 'pg_search'
gem 'pry-rails'
gem 'rack-cache'
gem 'redis', require: ['redis', 'redis/connection/hiredis']
gem 'sanitize'
gem 'sass-rails', '~> 4.0.3'
gem 'simple_form', github: 'plataformatec/simple_form'
gem 'sitemap_generator' #, github: 'kjvarga/sitemap_generator'
gem 'stamp'
gem 'sucker_punch'
gem 'turbolinks'
gem 'twitter'
gem 'uglifier', '>= 1.3.0'
gem 'unicorn'
gem 'uuidtools'

group :development, :test do
  gem 'dotenv-rails'
  gem 'jazz_hands', github: 'nixme/jazz_hands', branch: 'bring-your-own-debugger'
  gem 'pry-byebug'
  gem 'active_record_query_trace'
end

group :development do
  gem 'annotate', require: false
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'brakeman'
  gem 'foreman'
  gem 'guard-livereload'
  gem 'guard-rspec'
  gem 'meta_request'
  gem 'quiet_assets'
  gem 'rack-livereload'
  gem 'rails-erd'
  gem 'rubocop'
  gem 'spring'
  gem 'spring-commands-rspec'
end

group :test do
  gem 'capybara'
  gem 'poltergeist'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false, github: 'colszowka/simplecov'
end

group :production do
  gem 'le'
  gem 'newrelic_rpm'
  gem 'rails_12factor'
  gem 'rails_stdout_logging'
end
