default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     32
  host:     localhost
  port:     5432
  username: <%= ENV['POSTGRES_USER_NAME'] || 'uglst' %>
  <% if ENV['POSTGRES_PASSWORD'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
  <% end %>

development:
  <<: *default
  database: uglst_development

test: &test
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB_NAME'] || 'uglst_test' %>

production:
  <<: *default
  database: uglst_production

