default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     32
  host:     localhost
  port:     5432
  username: uglst
  password:
  template: template0

development:
  <<: *default
  database: uglst_development

test: &test
  <<: *default
  database: uglst_test
