default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5
  host:     localhost
  port:     5432
  username: <%= ENV['POSTGRES_USER_NAME'] || 'uglst' %>
  password:

development:
  <<: *default
  database: uglst_development

test: &test
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB_NAME'] || 'uglst_test' %>

production:
  <<: *default
  database: uglst_production
