default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  password:
  pool: 5
  port: <%= ENV['DEVELOPMENT_POSTGRES_PORT'] || 5432 %>
  username: uglst

development:
  <<: *default
  database: uglst_development

test: &test
  <<: *default
  database: uglst_test

production:
  <<: *default
  database: uglst_production

cucumber:
  <<: *test